service: factorial-function

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  endpoint: http://localhost:4566
  stage: local

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local

functions:
  factorial:
    handler: handler.handler
    events:
      - http:
          path: factorial
          method: GET
